version: '3'

tasks:
  full-redeploy:
    cmds:
      - docker compose build
      - docker compose down -v
      - docker compose up --build --detach
  # TODO: make it work with any service
  rollout-mw:
    cmds:
      - docker compose build mediawiki
      - docker rollout mediawiki -t 120
  stop: docker compose stop
  teardown: docker compose down -v
  # TODO: make it work with any service
  # TODO: make container indexes work too
  mw-bash: docker compose exec mediawiki /bin/bash
  maintenance-update:
    cmds:
      - docker compose exec mediawiki echo "$PWD"
      - docker compose exec mediawiki php var/www/html/w/maintenance/run.php update --quick
  up: docker compose up --detach
  up-preserve: docker compose up
  start: docker compose start --detach
  start-preserve: docker compose start
  restart:
    cmds:
      - docker compose stop
      - docker compose up --detach
  logs: docker compose logs -f
  init-elastic: docker compose exec mediawiki /bin/sh ./init_elastic.sh
